name: Test feature branch

on:
  push:
    branches:
      - feat/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 14.x
        uses: actions/setup-node@master
        with:
          node-version: 14.x
          registry-url: 'https://registry.npmjs.org'

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install dependencies # Install all deps
        run: yarn

      - name: Sync versions # Sync versions
        run: yarn syncprojects

      - name: Build demo app # Build Schematics and move
        run: yarn build:demo --base-href https://celtian.github.io/ngx-suspense-of/

      - name: Build ngx-suspense-of # Build
        run: yarn build

      - name: Run tests
        run: yarn test --configuration=ci
